### ISSUE TITLE
Release `@zitadel/proto`, `@zitadel/client` and `@zitadel/node` packages

### ISSUE THREAD

**Issue by peintnermax** [zitadel/typescript#288]
As we've a final release and upgraded to buf connect v2 https://github.com/connectrpc/connect-es/releases/tag/v2.0.0, we will publish our packages.

### Tasks

- [x] `@zitadel/proto`
- [x] `@zitadel/client`
- [x] `@zitadel/eslint-config`
- [x] `@zitadel/tailwind-config`
- [x] `@zitadel/prettier-config`
- [x] `@zitadel/ts-config`

**Comment by hifabienne** [comment]
@peintnermax can you estimate this issue?

**Comment by peintnermax** [comment]
done

**Comment by tafaust** [comment]
Hi @peintnermax. Where did you publish the packages to? I cannot find a @zitadel/client at npmjs.com
Thanks!

**Comment by hifabienne** [comment]
> Hi [@peintnermax](https://github.com/peintnermax). Where did you publish the packages to? I cannot find a @zitadel/client at npmjs.com Thanks!

https://www.npmjs.com/package/@zitadel/client

**Comment by tafaust** [comment]
Is it possible to add CommonJS support? The cjs exports from the package.json offer no relieve.
