### ISSUE TITLE
[Epic]: New typescript Login with OIDC flow Deployed

### ISSUE THREAD

**Issue by hifabienne** [zitadel/typescript#46]
As a end user I want to have the possiblity to deploy a ready to use login, and connect it to my ZITADEL instance.
Our goal is to have a first version ready, which can be selfhosted and does include the OIDC Standard.

Tasks for deploy login to vercel:
- [x] #48
- [x] #47
- [x] #49
- [ ] #51
- [x] #50
- [ ] Guide for different use cases (hosted login, customize hosted login, your own login in your application)
- [ ] Guide about how to only change the styling of the login

Tasks login ready with state of current hosted login:
- [x] https://github.com/zitadel/typescript/issues/15
- [x] https://github.com/zitadel/typescript/issues/18
- [x] https://github.com/zitadel/typescript/issues/17
- [x] https://github.com/zitadel/typescript/issues/37
- [ ] Implement missing scopes (metadata, roles, etc...)
- [ ] https://github.com/zitadel/zitadel/issues/8976
- [x] https://github.com/zitadel/typescript/issues/166
- [x] https://github.com/zitadel/typescript/issues/199

## Excluded
In the first version the following things will be excluded, but be implemented right after
- [ ] SAML
- [ ] Device Authorisation Flow
- [ ] Multi-tenancy (Needed to run the login for our Cloud offering)

**Comment by hifabienne** [comment]
@peintnermax should we close this issue for now? as we are now working towards the second milestone?

More informations about this can be found on our blog: https://zitadel.com/blog/typescript-login
Or on our docs: https://zitadel.com/docs/guides/integrate/login/hosted-login#hosted-login-version-2-beta
